version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/test/runtimes/browsers/"
    schedule:
      interval: "daily"
  - package-ecosystem: "npm"
    directory: "/test/runtimes/cloudflare/"
    schedule:
      interval: "daily"
